$script:DbPath=$null
function Get-Hash($Path){(Get-FileHash $Path -Algorithm SHA256).Hash}
function DB($Query,$Params=@{}){Invoke-SqliteQuery -DataSource $script:DbPath -Query $Query -SqlParameters $Params}
function Initialize-PlatformDatabase($DatabasePath,$MigrationFolder,$SeedFolder,$Seed=$true){
 Import-Module PSSQLite -ErrorAction Stop;$script:DbPath=$DatabasePath;$dir=Split-Path $DatabasePath -Parent;if(-not(Test-Path $dir)){New-Item $dir -ItemType Directory -Force|Out-Null}
 DB 'PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS SchemaVersion(Version INTEGER PRIMARY KEY,Name TEXT NOT NULL,AppliedOn TEXT NOT NULL,Checksum TEXT NOT NULL); CREATE TABLE IF NOT EXISTS MigrationHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,Version INTEGER,Name TEXT,StartedOn TEXT,CompletedOn TEXT,Status TEXT,Error TEXT,Checksum TEXT); CREATE TABLE IF NOT EXISTS SeedHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,SeedName TEXT UNIQUE,AppliedOn TEXT,Status TEXT,Error TEXT,Checksum TEXT);'|Out-Null
 foreach($f in Get-ChildItem $MigrationFolder -Filter *.sql|Sort Name){$v=[int]$f.BaseName.Split('_')[0];$hash=Get-Hash $f.FullName;$applied=DB 'SELECT * FROM SchemaVersion WHERE Version=@v' @{v=$v};if($applied){if($applied.Checksum -ne $hash){throw "Migration $v changed after application."};continue};DB 'INSERT INTO MigrationHistory(Version,Name,StartedOn,Status,Checksum) VALUES(@v,@n,@s,@t,@c)' @{v=$v;n=$f.Name;s=(Get-Date).ToString('s');t='Running';c=$hash}|Out-Null;try{DB 'BEGIN IMMEDIATE'|Out-Null;DB (Get-Content $f.FullName -Raw)|Out-Null;DB 'INSERT INTO SchemaVersion VALUES(@v,@n,@d,@c)' @{v=$v;n=$f.Name;d=(Get-Date).ToString('s');c=$hash}|Out-Null;DB 'COMMIT'|Out-Null;DB "UPDATE MigrationHistory SET CompletedOn=@d,Status='Success' WHERE Version=@v AND Status='Running'" @{d=(Get-Date).ToString('s');v=$v}|Out-Null}catch{try{DB 'ROLLBACK'|Out-Null}catch{};DB "UPDATE MigrationHistory SET CompletedOn=@d,Status='Failed',Error=@e WHERE Version=@v AND Status='Running'" @{d=(Get-Date).ToString('s');e=$_.Exception.Message;v=$v}|Out-Null;throw}}
 if($Seed){foreach($f in Get-ChildItem $SeedFolder -Filter *.sql|Sort Name){$hash=Get-Hash $f.FullName;$old=DB 'SELECT * FROM SeedHistory WHERE SeedName=@n' @{n=$f.Name};if($old){continue};try{DB (Get-Content $f.FullName -Raw)|Out-Null;DB "INSERT INTO SeedHistory(SeedName,AppliedOn,Status,Checksum) VALUES(@n,@d,'Success',@c)" @{n=$f.Name;d=(Get-Date).ToString('s');c=$hash}|Out-Null}catch{DB "INSERT OR REPLACE INTO SeedHistory(SeedName,AppliedOn,Status,Error,Checksum) VALUES(@n,@d,'Failed',@e,@c)" @{n=$f.Name;d=(Get-Date).ToString('s');e=$_.Exception.Message;c=$hash}|Out-Null;throw}}}
 $adminRole=DB "SELECT Id FROM RoleDefinitions WHERE RoleName='GlobalAdmin'";if($adminRole){DB 'INSERT OR IGNORE INTO UserRoles(UserAccount,RoleId,AssignedOn,AssignedBy) VALUES(@u,@r,@d,@a)' @{u=$env:USERNAME;r=$adminRole.Id;d=(Get-Date).ToString('s');a='Bootstrap'}|Out-Null}
}
function Add-Audit($Action,$Target,$Result,$Details='',$Correlation=''){DB 'INSERT INTO Audit(Timestamp,Administrator,Action,Target,Result,Details,CorrelationId) VALUES(@t,@u,@a,@g,@r,@d,@c)' @{t=(Get-Date).ToString('s');u=$env:USERNAME;a=$Action;g=$Target;r=$Result;d=$Details;c=$Correlation}|Out-Null}
function Test-Permission($Permission,$User=$env:USERNAME){[bool](DB 'SELECT 1 X FROM UserRoles ur JOIN RolePermissions rp ON rp.RoleId=ur.RoleId JOIN Permissions p ON p.Id=rp.PermissionId WHERE ur.UserAccount=@u AND p.PermissionName=@p UNION SELECT 1 FROM UserRoles ur JOIN RoleDefinitions r ON r.Id=ur.RoleId WHERE ur.UserAccount=@u AND r.RoleName=''GlobalAdmin'' LIMIT 1' @{u=$User;p=$Permission})}
function Sync-ReportCatalog($Root){foreach($f in Get-ChildItem $Root -Recurse -Filter *.ps1){$h=Get-Content $f.FullName -First 8;$n=(($h|?{$_ -match '^# ReportName:'})-replace '^# ReportName:\s*','');$d=(($h|?{$_ -match '^# Description:'})-replace '^# Description:\s*','');$a=(($h|?{$_ -match '^# ActionType:'})-replace '^# ActionType:\s*','');DB 'INSERT INTO ReportCatalog(Name,Category,Description,ActionType,ReportPath,LastDiscovered) VALUES(@n,@c,@d,@a,@p,@t) ON CONFLICT(ReportPath) DO UPDATE SET Name=@n,Category=@c,Description=@d,ActionType=@a,LastDiscovered=@t' @{n=$n;c=$f.Directory.Name;d=$d;a=$a;p=$f.FullName;t=(Get-Date).ToString('s')}|Out-Null}}
function Request-Approval($Action,$Target,$Details=''){$rule=DB 'SELECT * FROM ApprovalRules WHERE ActionName=@a AND Enabled=1' @{a=$Action};if(-not$rule){return $null};$id=[guid]::NewGuid().Guid;$expires=(Get-Date).AddMinutes([int]$rule.ExpiresMinutes).ToString('s');DB 'INSERT INTO ApprovalRequests(RequestType,RequestedBy,RequestedOn,TargetObject,ActionName,Details,ExpiresOn,CorrelationId) VALUES(@r,@u,@d,@t,@a,@x,@e,@c)' @{r='AdministrativeAction';u=$env:USERNAME;d=(Get-Date).ToString('s');t=$Target;a=$Action;x=$Details;e=$expires;c=$id}|Out-Null;$id}
function Test-Approved($Action,$Target){[bool](DB "SELECT 1 X FROM ApprovalRequests WHERE ActionName=@a AND TargetObject=@t AND Status='Approved' AND (ExpiresOn IS NULL OR ExpiresOn>@n) ORDER BY Id DESC LIMIT 1" @{a=$Action;t=$Target;n=(Get-Date).ToString('s')})}
function Approve-Request($Id,$Notes=''){DB "UPDATE ApprovalRequests SET Status='Approved' WHERE Id=@i" @{i=$Id}|Out-Null;DB 'INSERT INTO ApprovalHistory(RequestId,ActionTaken,Approver,ActionDate,Notes) VALUES(@i,@a,@u,@d,@n)' @{i=$Id;a='Approved';u=$env:USERNAME;d=(Get-Date).ToString('s');n=$Notes}|Out-Null}
function Reject-Request($Id,$Notes=''){DB "UPDATE ApprovalRequests SET Status='Rejected' WHERE Id=@i" @{i=$Id}|Out-Null;DB 'INSERT INTO ApprovalHistory(RequestId,ActionTaken,Approver,ActionDate,Notes) VALUES(@i,@a,@u,@d,@n)' @{i=$Id;a='Rejected';u=$env:USERNAME;d=(Get-Date).ToString('s');n=$Notes}|Out-Null}
function Get-Rows($Table){DB "SELECT * FROM $Table ORDER BY Id DESC"}
Export-ModuleMember -Function *
function Get-AuditRows($Search=''){DB 'SELECT * FROM Audit WHERE Action LIKE @s OR Target LIKE @s OR Administrator LIKE @s ORDER BY Id DESC LIMIT 2000' @{s="%$Search%"}}
Export-ModuleMember -Function Get-AuditRows
