CREATE TABLE IF NOT EXISTS SchemaVersion(Version INTEGER PRIMARY KEY,Name TEXT NOT NULL,AppliedOn TEXT NOT NULL,Checksum TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS MigrationHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,Version INTEGER,Name TEXT,StartedOn TEXT,CompletedOn TEXT,Status TEXT,Error TEXT,Checksum TEXT);
CREATE TABLE IF NOT EXISTS SeedHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,SeedName TEXT UNIQUE,AppliedOn TEXT,Status TEXT,Error TEXT,Checksum TEXT);
CREATE TABLE IF NOT EXISTS Audit(Id INTEGER PRIMARY KEY AUTOINCREMENT,Timestamp TEXT NOT NULL,Administrator TEXT,Action TEXT,Target TEXT,Result TEXT,Details TEXT,CorrelationId TEXT);
CREATE TABLE IF NOT EXISTS Executions(Id INTEGER PRIMARY KEY AUTOINCREMENT,Timestamp TEXT,Type TEXT,Name TEXT,Result TEXT,RowCount INTEGER,DurationMs INTEGER,Error TEXT);
CREATE TABLE IF NOT EXISTS Favorites(Id INTEGER PRIMARY KEY AUTOINCREMENT,ReportPath TEXT UNIQUE,DisplayName TEXT,Created TEXT);
CREATE TABLE IF NOT EXISTS SavedViews(Id INTEGER PRIMARY KEY AUTOINCREMENT,Name TEXT UNIQUE,ReportPath TEXT,TextFilter TEXT,NumericFilter INTEGER,Period TEXT,ContainsFilter TEXT,Created TEXT);
