CREATE TABLE IF NOT EXISTS ReportCatalog(Id INTEGER PRIMARY KEY AUTOINCREMENT,Name TEXT,Category TEXT,Description TEXT,ActionType TEXT,ReportPath TEXT UNIQUE,Enabled INTEGER DEFAULT 1,LastDiscovered TEXT);
CREATE TABLE IF NOT EXISTS ReportCache(Id INTEGER PRIMARY KEY AUTOINCREMENT,CacheKey TEXT UNIQUE,ReportPath TEXT,FilterJson TEXT,GeneratedOn TEXT,ExpiresOn TEXT,RowCount INTEGER,DataJson TEXT);
