CREATE TABLE IF NOT EXISTS AutomationJobs(Id INTEGER PRIMARY KEY AUTOINCREMENT,Name TEXT UNIQUE,JobType TEXT,Enabled INTEGER DEFAULT 1,ScheduleText TEXT,LastRun TEXT,NextRun TEXT,PayloadJson TEXT);
CREATE TABLE IF NOT EXISTS JobHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,JobId INTEGER,RunTime TEXT,Result TEXT,Details TEXT,FOREIGN KEY(JobId) REFERENCES AutomationJobs(Id));
