CREATE TABLE IF NOT EXISTS ApprovalRules(Id INTEGER PRIMARY KEY AUTOINCREMENT,ActionName TEXT UNIQUE,Enabled INTEGER DEFAULT 1,RequiredRole TEXT,ExpiresMinutes INTEGER DEFAULT 1440);
CREATE TABLE IF NOT EXISTS ApprovalRequests(Id INTEGER PRIMARY KEY AUTOINCREMENT,RequestType TEXT,RequestedBy TEXT,RequestedOn TEXT,Status TEXT DEFAULT 'Pending',TargetObject TEXT,ActionName TEXT,Details TEXT,ExpiresOn TEXT,CorrelationId TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS ApprovalHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,RequestId INTEGER,ActionTaken TEXT,Approver TEXT,ActionDate TEXT,Notes TEXT,FOREIGN KEY(RequestId) REFERENCES ApprovalRequests(Id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS IX_ApprovalRequests_Status ON ApprovalRequests(Status,RequestedOn);
